language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - pip install -e .\[all\]

script:
  - py.test tests --cov newlinejson --cov-report term-missing

after_success:
  - coveralls
