language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - pip install -r requirements-dev.txt
  - pip install .

script:
  - coverage run  --source=newlinejson -m py.test tests

after_success:
  - coveralls
